# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portman < Formula
  desc "Advanced Process & Port Manager"
  homepage "https://github.com/thejavator/portman"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thejavator/portman/releases/download/v1.0.0/portman_Darwin_x86_64.tar.gz"
      sha256 "cc35a95a944f9a9c0b0179501a66e8692ed8e443dfa98bd800b19a0e7dab0504"

      define_method(:install) do
        bin.install "portman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thejavator/portman/releases/download/v1.0.0/portman_Darwin_arm64.tar.gz"
      sha256 "7050d9bbe6c031860519ae749d61ab50082e8ac27d9d9e1bd90eabfdb7eae8bc"

      define_method(:install) do
        bin.install "portman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thejavator/portman/releases/download/v1.0.0/portman_Linux_x86_64.tar.gz"
      sha256 "fd9c240ed33459d5bbd9984865c279069a4606d2412bbe155e2ece1cc45108f8"
      define_method(:install) do
        bin.install "portman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thejavator/portman/releases/download/v1.0.0/portman_Linux_arm64.tar.gz"
      sha256 "af39e44aea5ec5a10c78ed5690f2aafd0c919d087f14bfa2d97ad21c1b19fa79"
      define_method(:install) do
        bin.install "portman"
      end
    end
  end

  test do
    system "#{bin}/portman --version"
  end
end
